#!/usr/bin/env python3
#

from argparse                           import ArgumentParser, RawTextHelpFormatter
import json
from lib.message_handler                import MessageHandler
from lib.std                            import pre

class MsgHandler(MessageHandler):
    def __init__(self):
        super(MsgHandler, self).__init__(archive_messages=False)


if __name__ == '__main__':
    app_description = '''Count how many kernels each person cranked in a cycle.
    '''
    app_epilog = '''
Examples:
    ./wip
    '''
    help_msgs = '''A json file of messages to be processed.'''

    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawTextHelpFormatter)
    parser.add_argument('msgs', nargs='?', help=help_msgs)
    args = parser.parse_args()

    msgs = {}
    total = 0
    mh = MsgHandler()
    try:
        with open(args.msgs, 'r') as fid:
            while fid:
                line = fid.readline()
                if line != '':
                    msg = json.loads(line)
                    mh.handle(msg)
                    total += 1
                else:
                    # End of file
                    #
                    break

    except json.decoder.JSONDecodeError:
        # Probably a empty string
        pass

    pre(f'{total} messages processed')
